language: node_js
node_js:
- '10'
deploy:
  provider: lambda
  function_name: The-Beastforge
  region: us-east-1
  role: arn:aws:lambda:us-east-1:917040255001:function:The-Beastforge
  runtime: nodejs10
  handler_name: handler
  access_key_id: AKIAJL6U47TQ2BQWIVLA
  secret_access_key:
    secure: U856DxPeWuQeZGoMNj/BHTptUhjByWj0OJYKNb8dRWh9RtQ7egChuztPANc+lB29Ud0bEaeCYdXnXNSDIlghjShb6sm2A9/un6EmMS2/q+BBY2qeUNcEcrrrxFKo5VZqByUiaYXWaA/y1L594xBNaL6HBQDvf/bDBG5wH3mWP+sqFRBD4aMxsr+jrXKptlXCDEaHNdQa7rzNw2UxfL2hxUxY28UaxTZgzHbkxs4Y70pAOlStyxm65ED2dc2SJNTJRYG9Di6qyKU7HiFHOxzwQ1lMFMzO/SdbYDLvcOZ0sL3F7yURzT9yf/R5iPV2TPTQZwJ4wD1BIpXXrhiFh1AH9BDu7MvgVSngWbs1AfPg0TzCffDd+KWxzgto9Q3ldrk2TIaZephVNZeDKM6DCIESH0qjk0Zq4EiIVewo3ll8zu/+nRA86RrJD2DBm6r+u1FPfTPwlCNAyIPiW9JDcADiHjugFumMgAbFPaDdlHaBj5d7WCK0PuuEhN11u82V+UDrTlAa8i1PnH/K10+E25NoToiBT1tR114QUhpBQ/Q6zQymNYeWOMUPEvHXJxMhfBJ4KGbpkJu0NGYcIAvlhdjrFEDyh3RVuxyMBQxL3XB4BPuhb957ufMtrY/8bEBfaFJSr5GvzCzl6Y+wzrDZbFBvFhp6ZOlua5jEX1J8qdE/+q0=
