language: node_js
node_js:
- '10'
before_install:
  # set up awscli packages
  - pip install --user awscli

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: deploy
      script: aws s3 sync build/ s3://the-beastforge --acl public-read